/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quicksort;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author gunny
 */
public class AnimationFrame extends javax.swing.JFrame {
    
   public Timer tick;
   public int t = 0;
   public Spy<Integer> spy;
//   Sorter insertSort = new InsertSorter ();
   public ArrayList<Snapshot> shotList;
   
   
   public void step() {
       t++;
       arrayView.repaint();
   }
   
   public class myPanel extends JPanel {
       public void paintComponent(Graphics g) {
           super.paintComponent(g);
              Snapshot b = spy.list.get(t% spy.list.size());           
              b.paintComponent(g);
              
              nSwaps.setText("Swaps: " + b.swaps);
              nComp.setText("Compares: "+ b.compares);
              
              nAction.setText(b.action);
       }
   }

    /**
     * Creates new form AnimationFrame
     */
    public AnimationFrame() {
         initComponents();
         RandomDataGenerator g = DataGenerators.almostSortedReversedIntegers;
         Sorter s = Sorters.bubbleSort;
         RandomData r = g.generate(10);
         CC<Integer> d = r.getData();
         //s.sort(d);
         spy = new Spy(d);
         s.sort(spy);
        nsorttype.setText("Sort Type: " + s.description());
        nrandomtype.setText("Random Type: " + r.getDescription());
        
        shotList = spy.list;
        
        tick = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                step();
            }

           
        });
    }
        
//        tick = new Timer(500, new ActionListener() {
//  public void actionPerformed(ActionEvent e) {
// 		step();}});
//        int [] sort = new int[20];
//        for(int i = 0; i<sort.length;i++)
//        {
//            sort[i] = sort.length-i;
//        }
//        Indexable<Integer> idc = new IntegerArray(sort);
//        spy = new Spy<Integer>(new CC<Integer>(new GtrInt(),idc));
//        
//        new InsertSorter().sort(spy);
//        
//        
//  tick.start();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        arrayView = new myPanel();
        nSwaps = new javax.swing.JLabel();
        nComp = new javax.swing.JLabel();
        nAction = new javax.swing.JLabel();
        nsorttype = new javax.swing.JLabel();
        nrandomtype = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushStart(evt);
            }
        });

        javax.swing.GroupLayout arrayViewLayout = new javax.swing.GroupLayout(arrayView);
        arrayView.setLayout(arrayViewLayout);
        arrayViewLayout.setHorizontalGroup(
            arrayViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        arrayViewLayout.setVerticalGroup(
            arrayViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        nSwaps.setText("Swaps:");

        nComp.setText("Compares:");

        nAction.setText("Action:");

        nsorttype.setText("Sort Type:");

        nrandomtype.setText("Random Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arrayView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nrandomtype)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(startButton)
                            .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(nSwaps)
                            .addGap(61, 61, 61))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nComp)
                                .addComponent(nAction)
                                .addComponent(nsorttype))
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(startButton)
                        .addGap(18, 18, 18)
                        .addComponent(nSwaps)
                        .addGap(45, 45, 45)
                        .addComponent(nComp)
                        .addGap(31, 31, 31)
                        .addComponent(nAction)
                        .addGap(18, 18, 18)
                        .addComponent(nsorttype)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(arrayView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(nrandomtype)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pushStart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushStart
        t=0;
        tick.start();
    }//GEN-LAST:event_pushStart

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arrayView;
    private javax.swing.JLabel nAction;
    private javax.swing.JLabel nComp;
    private javax.swing.JLabel nSwaps;
    private javax.swing.JLabel nrandomtype;
    private javax.swing.JLabel nsorttype;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
